### ISSUE TITLE
Quickly, show some code...anywhere...

### ISSUE THREAD

**Issue by kootenpv** [jundongl/scikit-feature#1]
It would be nice to know how to use the tool (also to show that it has a scikit interface).

**Comment by jundongl** [comment]
Hi kootenpv,

You can find a tutorial about how to use it here http://featureselection.asu.edu/tutorial.php.
Meanwhile, you can check the files in the example folder, it contains the examples for each feature selection algorithm.

Thanks.

**Comment by kootenpv** [comment]
@jundongl Thanks for your reply. I think it would be nice in your README to show an example already. Also, from what it seems, I'd consider changing those functions into `scikit-learn` style, that means using a Transformer class.

Instead of 

    from skfeature.function.similarity_based import fisher_score

from skfeature.transformers.similarity_based import FisherTransformer

    ft = FisherTransformer(num_features=5)
    ft.fit(X,y)
    transformed = ft.transform(X)
    transformed.shape
    (N, 5)
