### ISSUE TITLE
Return JMI Values

### ISSUE THREAD

**Issue by shubhakoundinyan** [jundongl/scikit-feature#15]
Is there a way I can get the JMI values being calculated for feature selection

**Comment by bacalfa** [comment]
Hi, @shubhakoundinyan. See if this is what you'd like to be available: https://github.com/jundongl/scikit-feature/pull/18/commits/e6e2c3c516f3e440ca215a5c69c232573a93a30d. Any suggestions are very welcome!

Example:

`F, J_CMI, MIfy = MRMR.mrmr(X, y)`
