### ISSUE TITLE
AttributeError: module 'skfeature.function.similarity_based.reliefF' has no attribute 'feature_ranking'

### ISSUE THREAD

**Issue by Andy1314Chen** [jundongl/scikit-feature#20]
I already install skfeature-chappers (1.0.2) ,but i got an AttributeError.

> AttributeError: module 'skfeature.function.similarity_based.reliefF' has no attribute 'feature_ranking'

**Comment by jundongl** [comment]
fixed

**Comment by k8iechen** [comment]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-15-fe3b2cfbef9c> in <module>
      1 score = fisher_score.fisher_score(X_train, y_train)
----> 2 idx = fisher_score.feature_ranking(score)
      3 
      4 num_fea = 5
      5 selected_features_train = X_train[:, idx[0:num_fea]]

**AttributeError: module 'skfeature.function.similarity_based.fisher_score' has no attribute 'feature_ranking'**

**Comment by ioannisgkouzionis** [comment]
Did anyone fix this error ?

**Comment by moumitam28** [comment]
Can anyone please look into this issue ?
