### ISSUE TITLE
Get " sparse matrix length is ambiguous; use getnnz() or shape[0]" error!

### ISSUE THREAD

**Issue by hiber-niu** [jundongl/scikit-feature#3]
corpus, categories = get_detail_content_category()

    vectorizer = TfidfVectorizer(max_df=1.0, max_features=6000, min_df=1,
                                 stop_words=get_cn_stopwords(),
                                 encoding='utf-8', decode_error='ignore',
                                 analyzer='word', tokenizer=cn_tokenize)

    X = vectorizer.fit_transform(corpus)
    y = categories

    idx = ICAP.icap(X, y, n_selected_features=1000)
    selected_X = X[:, idx[0:1000]]

After I run this code, i get error like title. I don't why, any help is appreciable.

**Comment by jundongl** [comment]
Could you try to make X and y to be full matrix?
