### ISSUE TITLE
Error occours when run an example on Python3.

### ISSUE THREAD

**Issue by Williamongh** [jundongl/scikit-feature#31]
Hi, thanks for your great work.
And I run into an error when I try to run the `test_MRMR.py` example.
It seems like some code are on the Python2.x, but when try to run on the Python3.x, it crashed.

Could you please update these part of code, make it fit in Python3?
Thx a lot.

**Comment by jscheithe** [comment]
Hi @Williamongh 

does the rest of the package work for you?

don't know if this is still relevant to you, but the code here on github for the actual functions (not the examples) seems to be Python 3 compatible. 

Try downloading the code directly from github if you didn't do so already.
