### ISSUE TITLE
Please add Python 3 support

### ISSUE THREAD

**Issue by rhiever** [jundongl/scikit-feature#5]
A large portion of the Python user base doesn't use Python 2 any more, and therefore can't use a package that doesn't support Python 3. Please add Python 3 support; it shouldn't take too much extra work.

**Comment by yitang** [comment]
+1

**Comment by hsiaoyi0504** [comment]
+1

**Comment by arose13** [comment]
I'm currently converting this to python 3 I can post it if you guys are interested

**Comment by jundongl** [comment]
arose13,

You are welcome to do that.

**Comment by jacobmontiel** [comment]
+1

**Comment by jonasteuwen** [comment]
I have it running under Python 3, apply 2to3, and most of it works already. Additionally, I changed some of the print error messages to a raise etc. (More Pythonic) and Cythonized some parts. Interested?

**Comment by aydindemircioglu** [comment]
somehow the alpus/scikit-feature did not work for me, so i forked my own.
there are certainly a lot of python conversions to do, but for my needs it works for now.
https://github.com/aydindemircioglu/scikit-feature

**Comment by bacalfa** [comment]
See https://github.com/bacalfa/scikit-feature/commit/d512eea2915385b97389ef59596655f5a0227f14

**Comment by hsiaoyi0504** [comment]
Why don't you just send a PR? I see there are many forked repos and claimed it works for Python3?

**Comment by bacalfa** [comment]
It's been merged. https://github.com/jundongl/scikit-feature/pull/18
